import { Box, Container, Grid,Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import axios from "axios";
import { productArr } from "../types/productResponse";
import { useEffect, useState } from "react";
import ItemCard from "../components/ItemCard";
import SelectForm from "../components/SelectForm";

const Home: NextPage<productArr> = ({ data }) => {
  const [products, setProducts] = useState(data);
  const [category,setCategory] = useState('all')

  useEffect(()=>{

    const filterWithCategory = async (category:string) =>{
      const filterProds = data.filter(product=>product.category === category)
      console.log("filtered",filterProds)
      setProducts(filterProds)
    }

    if(category !== "all"){
      filterWithCategory(category)
    }else{
      setProducts(data)
    }

    return ;
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[category])

  return (
    <div className={styles.container}>
      <Head>
        <title>Ecommerce Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.png" />
      </Head>

      <Box>
        
        <>
          <Box sx={{my:3,display:"flex",justifyContent:"space-between"}}>
            <Typography variant="h5" sx={{}}>Products</Typography>
            <SelectForm category={category} setCategory={setCategory}/>
          </Box>
          <Grid spacing={1} container>
            {products.map((item) => (
              <Grid  key={item.id} item xs={12} md={4} lg={3}>
                <ItemCard
                  id={item.id}
                  title={item.title}
                  price={item.price}
                  description={item.description.slice(0, 150)}
                  category={item.category}
                  image={item.image}
                  rating={item.rating}
                />
              </Grid>
            ))}
          </Grid>
        </>
      </Box>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await axios.get(`${process.env.baseURL}/api/products`);

  return {
    props: {
      data: data,
    },
  };
};
